language: ruby
rvm:
- 2.2.2
cache:
- bundler
gemfile: travisGemfile
install:
- bundle install
script: 
- bundle exec jekyll build && bundle exec htmlproof ./_site
branches:
  only:
  - master
  - source
notifications:
  email: true