language: ruby
rvm:
- 2.2.5
cache:
- bundler
gemfile: travisGemfile
install:
- gem install jekyll
- gem install html-proofer
- bundle install
script:
- bundle exec jekyll build 
- htmlproofer ./_site --disable-external, :allow_hash_href=>True 
branches:
  only:
  - master
  - source
notifications:
  email: true
sudo: false
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer