# Build settings
port: 4040
permalink   : /blog/:year/:title/
markdown    : kramdown
kramdown:
    input: GFM
highlighter : pygments
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Jesus Santander
description: "My personal website and blog"
keywords: "Radar, SAR, Commmunications, Data Analysis, SEO, blog, web"
url: https://jsantander.me
baseurl: ""
# baseurl: ""

# Google services
google_analytics: UA-88962240-1
# Disquis and repo
repo: https://github.com/rymnikski/rymnikski.github.io
disqus_shortname: "rymnikski"
disqus_site_shortname: "rymnikski"

# Author settings
author:
  name      : Jesus Santander
  job       : Telecommunications Engineer
  bio       : "Simplicity enthusiast, always looking for the best project and good coffee."
  thumb     : /images/avatar.png
  email     : jesus@jsantander.me
  url       : https://jsantander.me
  github    : https://github.com/rymnikski
  twitter   : https://twitter.com/rymnikski
  facebook  : https://facebook.com/rymnikski
  linkedin  : https://www.linkedin.com/in/rymnikski
  instagram : https://instagram.com/rymnikski
  skype     : j.alberto03

user: rymnikski

# navbar pages
navbar:
  - slug: blog
    title: Blog
  - slug: projects
    title: Projects
  - slug: resume
    title: Resume
  - slug: about
    title: About
    
#Colections
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/

  my_tags:
    output: true
    permalink: /blog/tag/:name/

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: "project"
    values:
      layout: project

exclude: ["vendor", "gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]


