permalink: /blog/:year/:month/:day/:title
email: jesus@jsantander.me
description: > # this means to ignore newlines until "baseurl:"
  My personal web page, and blog.
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rymnikski
github_username:  rymnikski

markdown: kramdown

kramdown:
    input: GFM

highlighter: rouge

# Google services
google_analytics: UA-88962240-1

#Colections
collections:
  my_categories:
    output: true
    permalink: /blog/category/:name/

  my_tags:
    output: true
    permalink: /blog/tag/:name/

# Handling Reading
exclude: [Gemfile, README.md]

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Outputting
permalink: /post/:title/
paginate: 5
paginate_path: '/blog/page/:num/'

defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
  -
    scope:
      path: ""
      type: my_categories
    values:
      layout: blog_by_category
  -
    scope:
      path: ""
      type: my_tags
    values:
      layout: blog_by_tag
  -
    scope:
      path: "project"
    values:
      layout: project